### ISSUE TITLE
[Feature Request] Include .prettierignore

### ISSUE THREAD

**Issue by sbley** [natterstefan/eslint-config-ns#23]
It would be cool to also have a shared extensible .prettierignore file in your sample project.

**Comment by natterstefan** [comment]
Hi @sbley.

This would be nice, but I am not sure if this is possible. Do you have an example for me, please?

**Comment by sbley** [comment]
Actually, no. I am not even sure if this file can be shared.

**Comment by dgagn** [comment]
Hey @sbley,

Maybe create a shell script that copies the .prettierignore to the project?

**Comment by natterstefan** [comment]
> Maybe create a shell script that copies the .prettierignore to the project?

I think that could work, although it only acts like a template. One has to adjust it manually if necessary. I am unaware of an `extend` feature for `.prettierignore`. 

Nevertheless, it is probably worth a try, but out of the scope of this repository. I hope you understand that.
