### ISSUE TITLE
Command failed: git describe --abbrev=0 fatal: No annotated tags can describe

### ISSUE THREAD

**Issue by mosherc** [natterstefan/eslint-config-ns#50]
# Bug Report

## Relevant information

When running our eslint script in our repo using your package, I get the observed results. It is being used in our private repo that has the required versions of eslint, node, and peer dependencies.

I'm not sure if this is a babel issue or issue with this package. I created a copy of your repo to fit my org's needs and that's where I originally saw this, but I also see it using your package too. I think it has to do something with the parser. I have the new parser installed `@babel/eslint-parser`. So I'm not really sure what's going on here :/

### Your Environment

- Browser: **\_**
- Browser version: **\_**
- OS: **MacOS 12.1**
- Package name: **eslint-config-ns**
- Package version: **2.0.0**

#### Steps to reproduce

Babel config:
```js
/* eslint-disable */
const { serve } = require('./build-config');

module.exports = function (api) {
  const isTest = api.env('test');

  const plugins = [
    ['babel-plugin-styled-components'],
    ['@babel/plugin-proposal-class-properties'],
    ['@babel/plugin-proposal-private-methods'],
    ['lodash'],
    [
      'relay',
      {
        artifactDirectory: './src/scripts/__generated__',
        compat: true,
        schema: './build/data/schema.json'
      }
    ]
  ];

  if (serve) {
    plugins.push(['react-refresh/babel']);
  }

  return {
    presets: [
      [
        '@babel/preset-env',
        {
          targets: isTest
            ? {
                node: '12.20.2'
              }
            : {
                chrome: 57,
                // etc.
              },
          bugfixes: true,
          corejs: 2,
          useBuiltIns: 'entry'
        }
      ],
      ['@babel/preset-react'],
      ['@babel/preset-flow']
    ],
    plugins
  };
};
```

```json
{
  /**
   * Overwrite or extend the default parserOptions
   */
  "parserOptions": {
    "requireConfigFile": false,
  },

  "extends": [
    "eslint-config-ns"
  ],
  "plugins": ["react", "flowtype", "jest", "import"],

  // Settings, rules, globals, etc.
  },
```

#### Observed Results

- I get a bunch of these:
```
fatal: No annotated tags can describe '<SHA of HEAD>'.
However, there were unannotated tags: try --tags.
```
and then a bunch of these:
```
/Users/path/to/file.js
  0:0  error  Parsing error: /Users/path/to/config/babel.config.js: Error while loading config - Command failed: git describe --abbrev=0
fatal: No annotated tags can describe '<SHA of HEAD>'.
However, there were unannotated tags: try --tags

#### Expected Results

- Eslint runs all the rules and lints the code

**Comment by natterstefan** [comment]
Hi @mosherc,

thanks for the report. Let's see how we can fix this together. Have you tried setting the `requireConfigFile` configuration to `true` in your `parserOptions`?  It's `false` in the example as it uses no custom babel config (https://github.com/natterstefan/eslint-config-ns/tree/main/packages/example-app).

> requireConfigFile (default true) can be set to false to allow @babel/eslint-parser to run on files that do not have a Babel configuration associated with them. This can be useful for linting files that are not transformed by Babel (such as tooling configuration files), though we recommend using the default parser via [glob-based configuration](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns). Note: @babel/eslint-parser will not parse any experimental syntax when no configuration file is found.
> ([src](https://www.npmjs.com/package/@babel/eslint-parser))

That might help and if so, I need to add some docs to the README. I am sorry for the troubles you have right now.

**Comment by mosherc** [comment]
So I tried updating a bunch of peer dependencies, and changing my app that is using your package to this eslint config snippet:
```
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "requireConfigFile": true,
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": ["react", "flowtype", "jest", "import"],
  "extends": [
    "eslint:recommended",
    "plugin:jest/recommended",
    "plugin:react-hooks/recommended",
    "plugin:prettier/recommended",
    "eslint-config-ns"
  ],
```
but I still get the same output. I tried without extending your config but keeping the peer dependency updates and I get the same output, so that leads me to believe maybe the peers updated are causing this to happen? In that case, here is a subset of my dev dependencies.
```
    "@babel/core": "7.14.0",
    "@babel/eslint-parser": "7.13.14",
    "@babel/plugin-proposal-class-properties": "7.13.0",
    "@babel/polyfill": "7.12.1",
    "@babel/preset-env": "7.14.1",
    "@babel/preset-flow": "7.13.13",
    "@babel/preset-react": "7.13.13",
    "@babel/register": "7.13.16",
    "babel-loader": "8.0.5",
    "eslint": "8.7.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-ns": "2.0.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-flowtype": "8.0.3",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jest": "26.0.0",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-react": "7.28.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "node-sass": "7.0.1",
    "prettier": "2.5.1",
```
 I also had to upgrade from node 12.x to 16.0.0

**Comment by mosherc** [comment]
Ok started over from scratch because I kept getting those errors even with no changes on our main branch.

I recloned the repo and started with your 1.6.0 js package. Everything worked and got a bunch of new eslint suggestions, probably from airbnb which we don't currently have. 

Then I added my org's package (based on your 1.6.0) and ran it (which has the exact same rules as our repo has already) and removed all of our rules that would be duplicated from extending, then ran it, and just got three eslint warnings! I didn't need to add `requireConfigFile` in either case too.

So I think I'm good now...I must have done something weird to cause this. I will close this and ping you again if it comes back up. This repo saved me a ton of time with setting up a shared config, so I'm glad we were able to figure it out, I appreciate the help!

**Comment by natterstefan** [comment]
Hi @mosherc,

I am glad it worked and thanks for the update. You're welcome. I am happy that this package helps others as well as it does help me in my projects.

Let me know any time if you have ideas, suggestions, or any other comments.

Take care and enjoy your day,
Stefan
